package com.wy.dao;

import com.wy.entity.SysRule;

import java.util.List;

public interface SysRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule
     *
     * @mbggenerated Fri Jun 19 15:15:49 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule
     *
     * @mbggenerated Fri Jun 19 15:15:49 CST 2020
     */
    int insert(SysRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule
     *
     * @mbggenerated Fri Jun 19 15:15:49 CST 2020
     */
    int insertSelective(SysRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule
     *
     * @mbggenerated Fri Jun 19 15:15:49 CST 2020
     */
    SysRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule
     *
     * @mbggenerated Fri Jun 19 15:15:49 CST 2020
     */
    int updateByPrimaryKeySelective(SysRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule
     *
     * @mbggenerated Fri Jun 19 15:15:49 CST 2020
     */
    int updateByPrimaryKey(SysRule record);
    /**
     * 查询全部
     * @return
     */
    List<SysRule> selectAll();
    
    
    /**
     * 根据用户组id查询,获得该用户组所有的菜单信息
     * @param groupId
     * @return
     */
    List<SysRule> selectRuleByGroupId(Integer groupId);
}