package com.wy.dao;

import com.wy.entity.SysUserGroup;

import java.util.List;

public interface SysUserGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group
     *
     * @mbggenerated Fri Jun 19 15:15:49 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group
     *
     * @mbggenerated Fri Jun 19 15:15:49 CST 2020
     */
    int insert(SysUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group
     *
     * @mbggenerated Fri Jun 19 15:15:49 CST 2020
     */
    int insertSelective(SysUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group
     *
     * @mbggenerated Fri Jun 19 15:15:49 CST 2020
     */
    SysUserGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group
     *
     * @mbggenerated Fri Jun 19 15:15:49 CST 2020
     */
    int updateByPrimaryKeySelective(SysUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group
     *
     * @mbggenerated Fri Jun 19 15:15:49 CST 2020
     */
    int updateByPrimaryKey(SysUserGroup record);
    
    /**
     * 根据字段查询列表
     * @param group
     * @return
     */
    List<SysUserGroup> selectByParam(SysUserGroup group);


    List<SysUserGroup> getAll();


}